# Generated by Django 4.0 on 2021-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainNews', '0002_category_news_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'New'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
    ]
